import DashboardNavbar from "src/examples/Navbars/DashboardNavbar";
import DashboardLayout from "src/layouts/DashboardLayout.tsx";
import MDBox from "src/mui-components/MDBox";
import MDTypography from "src/mui-components/MDTypography";
import DataTable from "src/examples/Tables/DataTable";

const SearchPageAlt = () => {
    return (
        <DashboardLayout>
            <DashboardNavbar/>
            <MDBox py={5}>

                <MDBox mb={2}>
                    <MDTypography variant="h2">Customer Search</MDTypography>
                </MDBox>

                <DataTable table={dataTableData} canSearch/>


            </MDBox>

        </DashboardLayout>
    );
};

export default SearchPageAlt;

const dataTableData = {
    columns: [
        { Header: "customer", accessor: "customer" },
        { Header: "primary contact", accessor: "primaryContact", width: "20%" },
        { Header: "users", accessor: "users", width: "7%" },
        { Header: "devices", accessor: "devices", width: "7%" },
        { Header: "customer since", accessor: "customerSince" },
    ],

    rows: [
        {
            primaryContact: "Hanny Baniard",
            customer: "Baorixile",
            users: 42,
            customerSince: "4/11/2021",
            devices: 474,
        },

        {
            primaryContact: "Lara Puleque",
            customer: "Cijangkar",
            users: 47,
            customerSince: "8/2/2021",
            devices: 387,
        },
        {
            primaryContact: "Torie Repper",
            position: "Administrative Officer",
            customer: "Montpellier",
            users: 25,
            customerSince: "4/21/2021",
            devices: 94,
        },
        {
            primaryContact: "Nat Gair",
            position: "Help Desk Technician",
            customer: "Imider",
            users: 57,
            customerSince: "12/6/2020",
            devices: 179,
        },
        {
            primaryContact: "Maggi Slowan",
            position: "Help Desk Technician",
            customer: "Jaunpils",
            users: 56,
            customerSince: "11/7/2020",
            devices: 440,
        },
        {
            primaryContact: "Marleah Snipe",
            position: "Account Representative II",
            customer: "Orekhovo-Borisovo Severnoye",
            users: 31,
            customerSince: "7/18/2021",
            devices: 404,
        },
        {
            primaryContact: "Georgia Danbury",
            position: "Professor",
            customer: "Gniezno",
            users: 50,
            customerSince: "10/1/2020",
            devices: 346,
        },
        {
            primaryContact: "Bev Castan",
            position: "Design Engineer",
            customer: "Acharnés",
            users: 19,
            customerSince: "1/14/2021",
            devices: 445,
        },
        {
            primaryContact: "Reggi Westney",
            position: "Financial Advisor",
            customer: "Piuí",
            users: 56,
            customerSince: "3/21/2021",
            devices: 441,
        },
        {
            primaryContact: "Bartholomeus Prosh",
            position: "Project Manager",
            customer: "Kelīshād va Sūdarjān",
            users: 28,
            customerSince: "5/27/2021",
            devices: 336,
        },
        {
            primaryContact: "Sheffy Feehely",
            position: "Software Consultant",
            customer: "Ndibène Dahra",
            users: 27,
            customerSince: "3/23/2021",
            devices: 473,
        },
        {
            primaryContact: "Euphemia Chastelain",
            position: "Engineer IV",
            customer: "Little Baguio",
            users: 63,
            customerSince: "5/1/2021",
            devices: 339,
        },
        {
            primaryContact: "Sharai Labat",
            position: "Geological Engineer",
            customer: "Býšť",
            users: 53,
            customerSince: "6/18/2021",
            devices: 403,
        },
        {
            primaryContact: "Nicolis Bremmell",
            position: "Analyst Programmer",
            customer: "Piraí do Sul",
            users: 27,
            customerSince: "1/29/2021",
            devices: 443,
        },
        {
            primaryContact: "Mattie Rait",
            position: "Budget/Accounting Analyst IV",
            customer: "Meziměstí",
            users: 30,
            customerSince: "6/9/2021",
            devices: 233,
        },
        {
            primaryContact: "Inger Gawkes",
            position: "Internal Auditor",
            customer: "Kangar",
            users: 27,
            customerSince: "4/20/2021",
            devices: 378,
        },
        {
            primaryContact: "Aldus Marginson",
            position: "Chief Design Engineer",
            customer: "Pingdingshan",
            users: 29,
            customerSince: "3/24/2021",
            devices: 223,
        },
        {
            primaryContact: "Wendel Swaite",
            position: "Speech Pathologist",
            customer: "Rubirizi",
            users: 22,
            customerSince: "6/5/2021",
            devices: 325,
        },
        {
            primaryContact: "Duffy Cicconetti",
            position: "Software Test Engineer I",
            customer: "Sendai-shi",
            users: 58,
            customerSince: "5/2/2021",
            devices: 335,
        },
        {
            primaryContact: "Mandi Paulley",
            position: "Account Representative III",
            customer: "Independencia",
            users: 25,
            customerSince: "4/27/2021",
            devices: 367,
        },
        {
            primaryContact: "Gladi Doorly",
            position: "Dental Hygienist",
            customer: "Longwy",
            users: 52,
            customerSince: "4/28/2021",
            devices: 306,
        },
        {
            primaryContact: "Johnnie Godfray",
            position: "Human Resources Manager",
            customer: "Afikpo",
            users: 31,
            customerSince: "4/15/2021",
            devices: 275,
        },
        {
            primaryContact: "Rudolph Jurczik",
            position: "Web Developer III",
            customer: "Jaciara",
            users: 36,
            customerSince: "11/19/2020",
            devices: 193,
        },
        {
            primaryContact: "Annmarie Fulbrook",
            position: "Cost Accountant",
            customer: "Lisala",
            users: 25,
            customerSince: "9/30/2020",
            devices: 423,
        },
        {
            primaryContact: "Daisey Nickolls",
            position: "Electrical Engineer",
            customer: "Xucheng",
            users: 60,
            customerSince: "2/26/2021",
            devices: 209,
        },
        {
            primaryContact: "Mordecai Dace",
            position: "Help Desk Technician",
            customer: "Busuanga",
            users: 22,
            customerSince: "1/29/2021",
            devices: 263,
        },
        {
            primaryContact: "Melisande Spall",
            position: "VP Accounting",
            customer: "Xiakouyi",
            users: 50,
            customerSince: "11/21/2020",
            devices: 290,
        },
        {
            primaryContact: "Karlik Sherrock",
            position: "GIS Technical Architect",
            customer: "Bagumbayan",
            users: 50,
            customerSince: "3/13/2021",
            devices: 217,
        },
        {
            primaryContact: "Constance Vinick",
            position: "Physical Therapy Assistant",
            customer: "Jiaoba",
            users: 46,
            customerSince: "3/23/2021",
            devices: 146,
        },
        {
            primaryContact: "Kimberlee Hoogendorp",
            position: "Dental Hygienist",
            customer: "Santo Antônio de Pádua",
            users: 63,
            customerSince: "4/11/2021",
            devices: 401,
        },
        {
            primaryContact: "Jephthah McIlvenny",
            position: "Executive Secretary",
            customer: "Poligny",
            users: 40,
            customerSince: "2/25/2021",
            devices: 397,
        },
        {
            primaryContact: "Claudetta Ivanchenkov",
            position: "Computer Systems Analyst III",
            customer: "Barranca de Upía",
            users: 22,
            customerSince: "2/4/2021",
            devices: 497,
        },
        {
            primaryContact: "Gordie Winterbottom",
            position: "General Manager",
            customer: "Kaeng Khro",
            users: 18,
            customerSince: "6/11/2021",
            devices: 85,
        },
        {
            primaryContact: "Yvor Ching",
            position: "Systems Administrator IV",
            customer: "Sobreira",
            users: 43,
            customerSince: "10/4/2020",
            devices: 445,
        },
        {
            primaryContact: "Marilin Swires",
            position: "Electrical Engineer",
            customer: "Longnan",
            users: 38,
            customerSince: "10/30/2020",
            devices: 123,
        },
        {
            primaryContact: "Tobey Fernan",
            position: "Compensation Analyst",
            customer: "Hushan",
            users: 31,
            customerSince: "3/17/2021",
            devices: 275,
        },
        {
            primaryContact: "Jan Trustrie",
            position: "Developer IV",
            customer: "Mashava",
            users: 34,
            customerSince: "12/3/2020",
            devices: 200,
        },
        {
            primaryContact: "Silva Linger",
            position: "Nurse Practicioner",
            customer: "Cosne-Cours-sur-Loire",
            users: 25,
            customerSince: "1/14/2021",
            devices: 490,
        },
        {
            primaryContact: "Jocko Oriel",
            position: "Design Engineer",
            customer: "Clisson",
            users: 61,
            customerSince: "12/2/2020",
            devices: 401,
        },
        {
            primaryContact: "Barbra Ready",
            position: "Paralegal",
            customer: "Xuedian",
            users: 29,
            customerSince: "11/3/2020",
            devices: 246,
        },
        {
            primaryContact: "Cynde Blakeslee",
            position: "Software Consultant",
            customer: "Kembangan",
            users: 23,
            customerSince: "1/9/2021",
            devices: 186,
        },
        {
            primaryContact: "Erminia O' Shea",
            position: "Analog Circuit Design manager",
            customer: "Tungawan",
            users: 51,
            customerSince: "12/8/2020",
            devices: 209,
        },
        {
            primaryContact: "Pietro Hoggins",
            position: "Account Coordinator",
            customer: "Lexington",
            users: 34,
            customerSince: "7/1/2021",
            devices: 245,
        },
        {
            primaryContact: "Cobb Fish",
            position: "VP Product Management",
            customer: "General Elizardo Aquino",
            users: 60,
            customerSince: "8/27/2020",
            devices: 201,
        },
        {
            primaryContact: "Goddart Zorzutti",
            position: "customer Assistant I",
            customer: "Hedi",
            users: 44,
            customerSince: "4/14/2021",
            devices: 89,
        },
        {
            primaryContact: "Joyce Gason",
            position: "VP Product Management",
            customer: "Jingzhou",
            users: 48,
            customerSince: "10/10/2020",
            devices: 285,
        },
        {
            primaryContact: "Juliet Lemm",
            position: "Junior Executive",
            customer: "Tečovice",
            users: 37,
            customerSince: "4/28/2021",
            devices: 479,
        },
        {
            primaryContact: "Filberte Dobrowolski",
            position: "Senior Cost Accountant",
            customer: "Puncakmanis",
            users: 55,
            customerSince: "8/21/2020",
            devices: 424,
        },
        {
            primaryContact: "Justinian Faraday",
            position: "Help Desk Technician",
            customer: "Bacong",
            users: 60,
            customerSince: "1/24/2021",
            devices: 369,
        },
        {
            primaryContact: "Amata Cahan",
            position: "Technical Writer",
            customer: "Hradec Králové",
            users: 56,
            customerSince: "9/22/2020",
            devices: 385,
        },
        {
            primaryContact: "Gunar Albrecht",
            position: "Tax Accountant",
            customer: "Chernivtsi",
            users: 52,
            customerSince: "6/30/2021",
            devices: 392,
        },
        {
            primaryContact: "Mal Deignan",
            position: "Senior Cost Accountant",
            customer: "Nefta",
            users: 57,
            customerSince: "7/18/2021",
            devices: 322,
        },
        {
            primaryContact: "Hamil Cicci",
            position: "Programmer Analyst IV",
            customer: "Fukushima-shi",
            users: 34,
            customerSince: "10/7/2020",
            devices: 471,
        },
        {
            primaryContact: "Stormie Peacop",
            position: "GIS Technical Architect",
            customer: "Emiliano Zapata",
            users: 57,
            customerSince: "10/21/2020",
            devices: 217,
        },
        {
            primaryContact: "Kayle Fallon",
            position: "Technical Writer",
            customer: "Midleton",
            users: 19,
            customerSince: "12/10/2020",
            devices: 294,
        },
        {
            primaryContact: "Cassandre Watters",
            position: "Technical Writer",
            customer: "Karang Tengah",
            users: 21,
            customerSince: "7/31/2021",
            devices: 213,
        },
        {
            primaryContact: "Cobb Fish",
            position: "VP Product Management",
            customer: "General Elizardo Aquino",
            users: 60,
            customerSince: "8/27/2020",
            devices: 201,
        },
    ],
};
